### ISSUE TITLE
Assets folder

### ISSUE THREAD

**Issue by JoshCarter8400** [JoshCarter8400/quarantine-movie-nights#2]
1. Icons for streaming services
2. Popcorn image for submit button
3. Background image 
4. Popcorn container to hold watchlist

**Comment by BeccsOmata** [comment]
Updated popcorn piece for SUBMIT button

**Comment by BeccsOmata** [comment]
Created/added background image

**Comment by BeccsOmata** [comment]
Created/added popcorn bucket

**Comment by BeccsOmata** [comment]
Created/added streaming service icons
Uploaded Mockup
