### ISSUE TITLE
Clicking Movie Card sends page back to top

### ISSUE THREAD

**Issue by BeccsOmata** [JoshCarter8400/quarantine-movie-nights#29]
We need to see if we can keep the page at the card that was clicked on, instead of shooting the user back up to the top

**Comment by csouthwick** [comment]
Need to get rid of the `<a>` tag on line 112 in the JavaScript file (`displayMovie()` function) so the text is just in the `<div>` on its own. The `<a>` tag with a hashtag inside causes a jump to the top of the page.

**Comment by BeccsOmata** [comment]
Hey Chris! I got rid of the HREF = '#' and that resolved it. Though it feels odd now that there is no indicator that it was added - you have to scroll to the list to check.
