### ISSUE TITLE
Populate genre dropdown

### ISSUE THREAD

**Issue by JoshCarter8400** [JoshCarter8400/quarantine-movie-nights#3]
https://api.themoviedb.org/3/genre/movie/list?api_key=0bd9398a9daad70a50c685a4f8c0a74b&language=en-US

**Comment by csouthwick** [comment]
For each `<option>`, the value attribute should be set to the genre ID from the API result above. The genre name will be shown in the dropdown box while the genre ID will be used in a later API call for getting the list of movie titles.
